[tool.poetry]
name = "vulnerability_analytics"
description = "Module for discovering further details about a crash"
authors = ["OpenCRS"]
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.12"
angr = "^9.2.24"
docker = "^6.1.2"
click = "^8.1.3"
rich = "^12.5.1"
nclib = "^1.0.2"
pathlib = "^1.0.1"
requests = "2.28.1"
povsim = { git = "https://github.com/mechaphish/povsim.git" }
compilerex = { git = "https://github.com/mechaphish/compilerex.git" }
rex = { git = "https://github.com/angr/rex.git" }
tracer = { git = "https://github.com/angr/tracer.git" }
# archinfo = "^9.2.24" # = { git = "https://github.com/angr/archinfo.git", branch = "master" }
# pyvex = { git = "https://github.com/angr/pyvex.git" }
# cle = { git = "https://github.com/angr/cle.git" }
# archr = { git = "https://github.com/angr/archr.git" }
setuptools = "^65.5.0"
keystone = "^22.0.0"
keystone-engine = "^0.9.2"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"
pylint = "^2.14.4"
pyproject-flake8 = "^0.0.1-alpha.5"
flake8-annotations = "^2.9.1"

[tool.poetry.scripts]
vulnerability_analytics = "vulnerability_analytics.cli:main"

[tool.pylint.MASTER]
init-hook="import sys; sys.path.append('.')"

[tool.pylint.MESSAGES_CONTROL]
disable="missing-function-docstring, missing-class-docstring, missing-module-docstring"

[tool.flake8]
extend-ignore = "ANN101,"
max-line-length=88
per-file-ignores = """
    ./**/__init__.py: F401
"""

[tool.black]
line-length = 79
preview = true
